//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace Fnet.SearchWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Search ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SearchService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUsersByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupByCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendListByNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SearchService() {
            this.Url = global::Fnet.Properties.Settings.Default.Fnet_SearchWS_Search_x0020_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUsersByEmailCompletedEventHandler GetUsersByEmailCompleted;
        
        /// <remarks/>
        public event GetUsersByNameCompletedEventHandler GetUsersByNameCompleted;
        
        /// <remarks/>
        public event GetGroupByCategoryCompletedEventHandler GetGroupByCategoryCompleted;
        
        /// <remarks/>
        public event GetGroupByNameCompletedEventHandler GetGroupByNameCompleted;
        
        /// <remarks/>
        public event GetFriendListCompletedEventHandler GetFriendListCompleted;
        
        /// <remarks/>
        public event GetFriendListByNameCompletedEventHandler GetFriendListByNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsersByEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUsersByEmail(string email) {
            object[] results = this.Invoke("GetUsersByEmail", new object[] {
                        email});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByEmailAsync(string email) {
            this.GetUsersByEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void GetUsersByEmailAsync(string email, object userState) {
            if ((this.GetUsersByEmailOperationCompleted == null)) {
                this.GetUsersByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByEmailOperationCompleted);
            }
            this.InvokeAsync("GetUsersByEmail", new object[] {
                        email}, this.GetUsersByEmailOperationCompleted, userState);
        }
        
        private void OnGetUsersByEmailOperationCompleted(object arg) {
            if ((this.GetUsersByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByEmailCompleted(this, new GetUsersByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsersByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUsersByName(string name) {
            object[] results = this.Invoke("GetUsersByName", new object[] {
                        name});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByNameAsync(string name) {
            this.GetUsersByNameAsync(name, null);
        }
        
        /// <remarks/>
        public void GetUsersByNameAsync(string name, object userState) {
            if ((this.GetUsersByNameOperationCompleted == null)) {
                this.GetUsersByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByNameOperationCompleted);
            }
            this.InvokeAsync("GetUsersByName", new object[] {
                        name}, this.GetUsersByNameOperationCompleted, userState);
        }
        
        private void OnGetUsersByNameOperationCompleted(object arg) {
            if ((this.GetUsersByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByNameCompleted(this, new GetUsersByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupByCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGroupByCategory(string category) {
            object[] results = this.Invoke("GetGroupByCategory", new object[] {
                        category});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupByCategoryAsync(string category) {
            this.GetGroupByCategoryAsync(category, null);
        }
        
        /// <remarks/>
        public void GetGroupByCategoryAsync(string category, object userState) {
            if ((this.GetGroupByCategoryOperationCompleted == null)) {
                this.GetGroupByCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupByCategoryOperationCompleted);
            }
            this.InvokeAsync("GetGroupByCategory", new object[] {
                        category}, this.GetGroupByCategoryOperationCompleted, userState);
        }
        
        private void OnGetGroupByCategoryOperationCompleted(object arg) {
            if ((this.GetGroupByCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupByCategoryCompleted(this, new GetGroupByCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGroupByName(string name) {
            object[] results = this.Invoke("GetGroupByName", new object[] {
                        name});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupByNameAsync(string name) {
            this.GetGroupByNameAsync(name, null);
        }
        
        /// <remarks/>
        public void GetGroupByNameAsync(string name, object userState) {
            if ((this.GetGroupByNameOperationCompleted == null)) {
                this.GetGroupByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupByNameOperationCompleted);
            }
            this.InvokeAsync("GetGroupByName", new object[] {
                        name}, this.GetGroupByNameOperationCompleted, userState);
        }
        
        private void OnGetGroupByNameOperationCompleted(object arg) {
            if ((this.GetGroupByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupByNameCompleted(this, new GetGroupByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFriendList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetFriendList(int userID) {
            object[] results = this.Invoke("GetFriendList", new object[] {
                        userID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendListAsync(int userID) {
            this.GetFriendListAsync(userID, null);
        }
        
        /// <remarks/>
        public void GetFriendListAsync(int userID, object userState) {
            if ((this.GetFriendListOperationCompleted == null)) {
                this.GetFriendListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendListOperationCompleted);
            }
            this.InvokeAsync("GetFriendList", new object[] {
                        userID}, this.GetFriendListOperationCompleted, userState);
        }
        
        private void OnGetFriendListOperationCompleted(object arg) {
            if ((this.GetFriendListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendListCompleted(this, new GetFriendListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFriendListByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetFriendListByName(int userID, string input) {
            object[] results = this.Invoke("GetFriendListByName", new object[] {
                        userID,
                        input});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendListByNameAsync(int userID, string input) {
            this.GetFriendListByNameAsync(userID, input, null);
        }
        
        /// <remarks/>
        public void GetFriendListByNameAsync(int userID, string input, object userState) {
            if ((this.GetFriendListByNameOperationCompleted == null)) {
                this.GetFriendListByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendListByNameOperationCompleted);
            }
            this.InvokeAsync("GetFriendListByName", new object[] {
                        userID,
                        input}, this.GetFriendListByNameOperationCompleted, userState);
        }
        
        private void OnGetFriendListByNameOperationCompleted(object arg) {
            if ((this.GetFriendListByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendListByNameCompleted(this, new GetFriendListByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetUsersByEmailCompletedEventHandler(object sender, GetUsersByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetUsersByNameCompletedEventHandler(object sender, GetUsersByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetGroupByCategoryCompletedEventHandler(object sender, GetGroupByCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetGroupByNameCompletedEventHandler(object sender, GetGroupByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetFriendListCompletedEventHandler(object sender, GetFriendListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetFriendListByNameCompletedEventHandler(object sender, GetFriendListByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendListByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendListByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591